### ISSUE TITLE
Some suggestions about coding style.

### ISSUE THREAD

**Issue by whatcall** [HEKR-Cloud/HEKR-MCU-SDK#1]
1. Function or variable names like Function_Name_Foo or Variable_Name_Blabla could be improved. It seems either FunctionNameFoo or function_name_foo is better practice. Same rule for variable naming and file naming.
2. Header file should not include "static" function declarations.
3. Module (or file) scoped variables should be defined as "static" to keep them only seen in this file.

**Comment by BearZPY** [comment]
Thank you for your suggestions. The related changes will be reflected in the new version.  You can focus on the new version.

**Comment by BearZPY** [comment]
Version has been updated. You can view the latest version.
Thank you for your suggestions.
